[package]
name = "terrek"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "terrek"
path = "Terrek_Cli/main.rs"


[dependencies]
tui = "0.19"           # TUI library for layouts and widgets
crossterm = "0.25"     # Crossterm for terminal management
portable-pty = "0.9.0"
anyhow = "1.0.100"
chrono = "0.4.43"
termios = "0.3.3"
rusqlite = "0.38.0"
sqlx = "0.8.6"
