//! Shell hooks that report each command to Terrek through a private OSC sequence:
//!
//! ```text
//! ESC ] 7777 ; start ; <b64 command> BEL          before a command runs   (zsh, fish)
//! ESC ] 7777 ; done ; <exit> ; <b64 cmd> ; <b64 cwd> BEL   after it finishes
//! ESC ] 7777 ; prompt BEL                          every time a prompt is drawn
//! ```
//!
//! Terrek strips these from the output, so users never see them. The user's own
//! rc files are sourced first; nothing on disk is modified.

use anyhow::Result;
use std::fs;
use std::path::Path;
use tempfile::TempDir;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellKind {
    Zsh,
    Bash,
    Fish,
    Other,
}

impl ShellKind {
    pub fn detect(program: &str) -> Self {
        let name = Path::new(program)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(program)
            .trim_start_matches('-');
        match name {
            "zsh" => Self::Zsh,
            "bash" => Self::Bash,
            "fish" => Self::Fish,
            _ => Self::Other,
        }
    }

    pub fn is_supported(self) -> bool {
        !matches!(self, Self::Other)
    }
}

/// How to launch the shell with hooks installed. Keep it alive until the shell exits.
pub struct Integration {
    pub args: Vec<String>,
    pub env: Vec<(String, String)>,
    _dir: Option<TempDir>,
}

impl Integration {
    pub fn none() -> Self {
        Self {
            args: vec!["-i".into()],
            env: vec![],
            _dir: None,
        }
    }

    pub fn prepare(kind: ShellKind) -> Result<Self> {
        match kind {
            ShellKind::Zsh => {
                let dir = tempfile::Builder::new().prefix("terrek-zsh-").tempdir()?;
                fs::write(dir.path().join(".zshenv"), ZSH_ENV)?;
                fs::write(dir.path().join(".zshrc"), format!("{ZSH_RC}\n{ZSH_HOOKS}"))?;
                let user_zdotdir = std::env::var("ZDOTDIR")
                    .or_else(|_| std::env::var("HOME"))
                    .unwrap_or_default();
                Ok(Self {
                    args: vec!["-i".into()],
                    env: vec![
                        ("ZDOTDIR".into(), dir.path().display().to_string()),
                        ("TERREK_USER_ZDOTDIR".into(), user_zdotdir),
                    ],
                    _dir: Some(dir),
                })
            }
            ShellKind::Bash => {
                let dir = tempfile::Builder::new().prefix("terrek-bash-").tempdir()?;
                let rc = dir.path().join("bashrc");
                fs::write(&rc, BASH_RC)?;
                Ok(Self {
                    args: vec!["--rcfile".into(), rc.display().to_string(), "-i".into()],
                    env: vec![],
                    _dir: Some(dir),
                })
            }
            ShellKind::Fish => {
                let dir = tempfile::Builder::new().prefix("terrek-fish-").tempdir()?;
                let script = dir.path().join("terrek.fish");
                fs::write(&script, FISH_HOOKS)?;
                let quoted = script.display().to_string().replace('\'', "\\'");
                Ok(Self {
                    args: vec![
                        "-i".into(),
                        "--init-command".into(),
                        format!("source '{quoted}'"),
                    ],
                    env: vec![],
                    _dir: Some(dir),
                })
            }
            ShellKind::Other => Ok(Self::none()),
        }
    }
}

/// zsh reads `$ZDOTDIR/.zshenv` then `$ZDOTDIR/.zshrc`. We point ZDOTDIR at a temp dir,
/// source the user's real files from there, then hand ZDOTDIR back.
const ZSH_ENV: &str = r#"# Generated by Terrek
__terrek_zdotdir="$ZDOTDIR"
ZDOTDIR="${TERREK_USER_ZDOTDIR:-$HOME}"
[[ -f "$ZDOTDIR/.zshenv" ]] && builtin source "$ZDOTDIR/.zshenv"
TERREK_USER_ZDOTDIR="$ZDOTDIR"
ZDOTDIR="$__terrek_zdotdir"
"#;

const ZSH_RC: &str = r#"# Generated by Terrek
ZDOTDIR="$TERREK_USER_ZDOTDIR"
unset __terrek_zdotdir
[[ -f "$ZDOTDIR/.zshrc" ]] && builtin source "$ZDOTDIR/.zshrc"
"#;

const ZSH_HOOKS: &str = r#"
__terrek_b64() { builtin printf '%s' "$1" | command base64 | command tr -d '\n'; }
__terrek_preexec() {
  __terrek_running=1
  builtin printf '\033]7777;start;%s\007' "$(__terrek_b64 "$1")"
}
__terrek_precmd() {
  local ec=$?
  if [[ -n "$__terrek_running" ]]; then
    __terrek_running=
    builtin printf '\033]7777;done;%s;;%s\007' "$ec" "$(__terrek_b64 "$PWD")"
  fi
  builtin printf '\033]7777;prompt\007'
  return $ec
}
autoload -Uz add-zsh-hook
add-zsh-hook preexec __terrek_preexec
# First in line so it sees the command's exit status before other hooks change it.
precmd_functions=(__terrek_precmd ${precmd_functions[@]})
# Terrek sends this after printing below the prompt, so the prompt is drawn again.
__terrek_redraw() { zle reset-prompt }
zle -N __terrek_redraw
bindkey -M emacs '\e[9999~' __terrek_redraw
bindkey -M viins '\e[9999~' __terrek_redraw
"#;

/// Bash has no preexec hook, so the command comes from `history 1` in PROMPT_COMMAND and a
/// changed history number tells us a command actually ran (pressing Enter alone doesn't count).
const BASH_RC: &str = r#"# Generated by Terrek
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
__terrek_b64() { builtin printf '%s' "$1" | command base64 | command tr -d '\n'; }
# Bash loads HISTFILE after the rc files, so the baseline is taken at the first prompt.
__terrek_last_hist=__init__
__terrek_precmd() {
  local ec=$? n cmd
  read -r n cmd <<< "$(HISTTIMEFORMAT= builtin history 1)"
  if [ "$__terrek_last_hist" = __init__ ]; then
    __terrek_last_hist=$n
  elif [ -n "$n" ] && [ "$n" != "$__terrek_last_hist" ]; then
    __terrek_last_hist=$n
    builtin printf '\033]7777;done;%s;%s;%s\007' "$ec" "$(__terrek_b64 "$cmd")" "$(__terrek_b64 "$PWD")"
  fi
  builtin printf '\033]7777;prompt\007'
  return $ec
}
PROMPT_COMMAND="__terrek_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"
bind '"\e[9999~": redraw-current-line' 2>/dev/null
"#;

const FISH_HOOKS: &str = r#"# Generated by Terrek
function __terrek_b64
    printf '%s' $argv[1] | command base64 | command tr -d '\n'
end
function __terrek_preexec --on-event fish_preexec
    printf '\033]7777;start;%s\007' (__terrek_b64 "$argv[1]")
end
function __terrek_postexec --on-event fish_postexec
    set -l ec $status
    printf '\033]7777;done;%s;;%s\007' $ec (__terrek_b64 "$PWD")
end
function __terrek_prompt --on-event fish_prompt
    printf '\033]7777;prompt\007'
end
bind \e\[9999~ repaint
bind -M insert \e\[9999~ repaint 2>/dev/null
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_shells_from_paths() {
        assert_eq!(ShellKind::detect("/bin/zsh"), ShellKind::Zsh);
        assert_eq!(ShellKind::detect("-bash"), ShellKind::Bash);
        assert_eq!(ShellKind::detect("/opt/homebrew/bin/fish"), ShellKind::Fish);
        assert_eq!(ShellKind::detect("/bin/sh"), ShellKind::Other);
    }

    #[test]
    fn zsh_integration_points_zdotdir_at_generated_files() {
        let integration = Integration::prepare(ShellKind::Zsh).unwrap();
        let zdotdir = &integration
            .env
            .iter()
            .find(|(k, _)| k == "ZDOTDIR")
            .unwrap()
            .1;
        let rc = fs::read_to_string(Path::new(zdotdir).join(".zshrc")).unwrap();
        assert!(rc.contains("add-zsh-hook preexec __terrek_preexec"));
        assert!(Path::new(zdotdir).join(".zshenv").exists());
    }
}
