name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      # Debug step 
      - name: Debug build output
        run: |
          echo "Listing target/release:"
          ls -R target || dir target
        shell: bash

      # Unix (Linux + macOS)
      - name: Prepare binary (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir -p release
          cp target/release/terrek release/terrek-${{ matrix.os }}
          chmod +x release/terrek-${{ matrix.os }}

      # Windows (PowerShell)
      - name: Prepare binary (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir release
          Copy-Item target/release/terrek.exe release/terrek-${{ matrix.os }}.exe
        shell: pwsh

      #  Upload release assets
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*